application: tiramisulibrary
version: 1
runtime: python
api_version: 1


handlers:

- url: /static
  static_dir: static
  expiration: "7d"

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css

- url: /.*
  script: bootstrap.py
